version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testN0Nprod #TODO: Unsecure, not for production use
      POSTGRES_DB: bookstore
    volumes:
      - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testN0Nprod
